planning.md

added our planning document starter

Document planning

---

lib/board.rb
spec/board_spec.rb

made and passed test for key values

test: board key values

---

lib/board.rb
lib/scratchpad.rb
spec/board_spec.rb

New test for board spaces, and display mechanism for hash.
Exploring also, nested array options.

Board spaces testing

---

lib/board.rb
spec/board_spec.rb

added hardcoded value strings for rows, columns, and diagonals, referenced to the display method

Hash correlation

---

lib/board.rb
spec/board_spec.rb

Organized and categorized tests
Added 'possible wins' method to compile all the rows/columns/diags into a single array
Added winner? method to see if anyone has won.
- we might consider moving this to another class later potentially...

Board Checker Functionality

---

lib/board.rb
spec/board_spec.rb

Added tie? methods and tests
Designed a tie scenario board to test
Improved winner? method and tests

Board tweaks

---

lib/board.rb
lib/playground.rb
lib/turn.rb
spec/turn_spec.rb

Complete valid_column? method to check for an acceptable play selection.

Turn class

---

lib/scratchpad.rb
lib/turn.rb
spec/board_spec.rb
spec/turn_spec.rb

this is horribly ugly and probably should be refactored, but it achieves what we need for now

Turn class Add token method

---

lib/board.rb
lib/playground.rb
spec/board_spec.rb
spec/turn_spec.rb

New horizontal_win methods
New vertical_win methods
New pretty_print method
and other refactors.

Refactor Display and Win Mechanisms To Simplify Code

---

lib/board.rb
spec/board_spec.rb

removed the now unnecessary horizontal and vertical win? methods and variables. folded diagonal win method into #search_for_winner method. added test for diagonal win based on new method

fixed: cleanup and removal of unneeded code and methods

---

lib/turn.rb

refactored messy brute force drop_token method and ran test to confirm

refactor: drop_token method

---

lib/game.rb
lib/playground.rb
spec/game_spec.rb

Several game class functions
Menu prompt and selection options for start/quit

Build game class

---

lib/game.rb
lib/playground.rb
spec/game_spec.rb

added player and computer turns, looped game play, TESTED GAME

Player turns

---

lib/board.rb
lib/game.rb
lib/space.rb
lib/turn.rb
runner.rb
spec/board_spec.rb
spec/game_spec.rb

Lots of small refactorings, extracting methods, and removal of "reaching through objects".
Some display modifications, and enabling game restart after win.

Code cleanup

---

lib/game.rb
lib/playground.rb
runner.rb

pulled tie condition method out of game_play and made it its own method

refactor: tie method in game class

---

lib/game.rb

fixed the issues from previous PR that were causing failure to break out of game_play loop

fix: refactor loop errors

---

lib/playground.rb

Got a working algo to check diagonals.

feat: Build diagonal search mechanic in Playground

---

lib/board.rb
lib/game.rb

Refactoring and renaming things in board & game class.
Cleaning up the XXXX || OOOO comparisons into single method.
All 21 tests pass currently, game works with horiz, diag, vertical wins/losses.

fix: Refactor board class methods and clean up win check

---

lib/board.rb
spec/board_spec.rb

added tests for diagonal win method and component methods -- WILL NEED TO FIX TO PASS WITH CONCURRENT CHANGES TO LIB

tests: added more test coverage for diagonal win components

---

.gitignore
Gemfile.lock
lib/game.rb

cleaned up some of the two player stuff to make them more readable and concise

refactor: cleaned two player methods

---

lib/game.rb
runner.rb

fix: rearranged menu options

---

assets/record.csv
assets/record.txt
lib/game.rb
lib/record.rb
spec/game_spec.rb
spec/record_spec.rb

Implemented Record class into two player games.

Record keeping

---

lib/board.rb
lib/game.rb
lib/turn.rb

cleaned up the UI to be more user friendly. fixed bug with column selection

fix: minor cleanup and quality of life changes

---

assets/record.csv
lib/record.rb
spec/game_spec.rb
spec/record_spec.rb

Complete Record class test suite
Gameplay test etc.

fix: All tests passing, game play strong

---

README.md

Quick update to the readme file for completion.

feat: Add more robust readme.md
